---
title: "Practice Project Description"
date: " "
output: html_document
---

## Overview

This document contains instructions on the practice project for STA 207 Winter 2022. This document is made with `R markdown`. The `rmd` file to generate this document is available on the course website. 

## Background

In this project, we study the dataset from an influential randomized experiment. The Tennesses  Student/Teacher Achievement Ratio study (a.k.a. Project STAR) was conducted in the late 1980s to evaluate the effect of class sizes on test scores. This dataset has been used as a classic examples in many textbooks and research papers. You are encouraged to read more about the experiment design and how others analyze this dataset. This document only provides a brief explanation of the dataset for this course project. 

The study randomly assigned students to small classes, regular classes, and regular classes with a teacher's aide. In order to randomize properly, schools were enrolled only if they had enough student body to have at least one class of each type. Once the schools were enrolled, students were randomly assigned to the three types of classes, and one teacher was randomly assigned to each class. 

The dataset contains scaled scores for math and reading from kindergarten to 3rd grade. We will only examine the math scores in 1st grade in this project. The primary question of interest is whether there is __any differences in math scaled scores in 1st grade across class types__, and if so, a secondary question of interest is __which class type is associated with the highest math scaled scores in 1st grade__. In particular, we will treat each teacher as the basic unit of our analysis. To put it in another way, we will treat each class (uniquely identified by its assigned teacher) as an observation. Noting that there are multiple students in each class, some data manipulation are warranted. 


## Suggested outline 

The following list provides one potential structure of the data analysis report. A detailed template for this project is provided in a separate RMD file. The  detailed template is provided as a learning tool for the first data analysis project in this course. There will not be any templates for future projects. 

1. Introduce the data set and the questions of interest.

2. Review the background of Project STAR, and **find the data set from the Internet**. 

3. Explore this dataset and generate summary statistics that you find informative, and explain your findings.  In particular,
    a. obtain math scaled scores in the 1st grade with teachers as the unit,
    b. and investigate the relationship between school indicator, class types, and math scaled scores in 1st grade. 

4.  Propose an appropriate model to answer the questions of interest. The model should include the school indicator as a factor/regressor to adjust for. 
    a. Explain your notation. 
    b. State assumptions for your model. 
    c. Explain why your model is appropriate for this task. 

5.  Fit the proposed model in (4) and explain your results. In particular, comment on the causal effects from your analysis.

6.  Conduct model diagnostics and/or sensitivity analysis. 

7. Conclude your analysis with an discussion of your findings and caveats of your approach. 
